CREATE TABLE cards (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word       text NOT NULL,
    trans_word text NOT NULL,
    plural     text
);

CREATE TABLE themas (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE sentances (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      text NOT NULL,
    translate text NOT NULL
);

-- ON DELETE CASCADE on both join tables: the services delete a card or a sentence
-- without unbinding it first, so the bindings have to go away on their own.
CREATE TABLE themas_cards (
    thema_id integer NOT NULL REFERENCES themas (id) ON DELETE CASCADE,
    card_id  integer NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    PRIMARY KEY (thema_id, card_id)
);

CREATE TABLE cards_sentance (
    card_id     integer NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    sentance_id integer NOT NULL REFERENCES sentances (id) ON DELETE CASCADE,
    PRIMARY KEY (card_id, sentance_id)
);

-- the PK covers lookups by the leading column; these cover the other direction
CREATE INDEX idx_themas_cards_card_id ON themas_cards (card_id);
CREATE INDEX idx_cards_sentance_sentance_id ON cards_sentance (sentance_id);
