spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:laguagecarddb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgrespw}

server.port=${SERVER_PORT:8080}

server.error.include-message=always
server.error.include-binding-errors=always
